### ISSUE TITLE
Invalid URL Errors during GitlabFillerProcessor execution

### ISSUE THREAD

**Issue by faisyl** [immobiliare/backstage-plugin-gitlab#119]
Adding backstage-plugin-gitlab causes entity postprocessing to start failing for the gitlab provider with the following error:

```
backstage-new-backstage-1  | {"entity":"group:default/dev1","level":"warn","location":"url:git.panka.in/teams/dev1","message":"Processor GitlabFillerProcessor threw an error while postprocessing; caused by TypeError [ERR_INVALID_URL]: Invalid URL","plugin":"catalog","service":"backstage","type":"plugin"}
backstage-new-backstage-1  | {"entity":"group:default/gitlab-instance-97cc0186","level":"warn","location":"url:git.panka.in/teams/gitlab-instance-97cc0186","message":"Processor GitlabFillerProcessor threw an error while postprocessing; caused by TypeError [ERR_INVALID_URL]: Invalid URL","plugin":"catalog","service":"backstage","type":"plugin"}
backstage-new-backstage-1  | {"entity":"user:default/root","level":"warn","location":"url:git.panka.in/root","message":"Processor GitlabFillerProcessor threw an error while postprocessing; caused by TypeError [ERR_INVALID_URL]: Invalid URL","plugin":"catalog","service":"backstage","type":"plugin"}
backstage-new-backstage-1  | {"entity":"user:default/user1","level":"warn","location":"url:git.panka.in/user1","message":"Processor GitlabFillerProcessor threw an error while postprocessing; caused by TypeError [ERR_INVALID_URL]: Invalid URL","plugin":"catalog","service":"backstage","type":"plugin"}
```
The baseUrl and host entries are set correctly:

```
integrations:
  gitlab:
    - host: git.panka.in
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://git.panka.in/api/v4
      baseUrl: https://git.panka.in
```
Anything I am missing in my configuration here?

**Comment by antoniomuso** [comment]
Hi @faisyl, It seems that your locations are not valid URLs. they don't have the protocol... So I think the problem is relative to the configuration you have passed in.
In fact, seems that you have added to the `allowedKinds` configuration the Kinds `Group` and `User`, you can fix by removing it as follow:

```diff
gitlab:
-      allowedKinds: ['Component', 'User', 'Group' ]
+      allowedKinds: ['Component']
```

**Comment by faisyl** [comment]
I have orgEnabled for the gitlab discovery plugin. Here's my complete app-config. I can't see anything here that isn't URLized correctly. Am I missing something  here?

```
app:
  title: Panka Backstage
  baseUrl: https://genesis.panka.in

organization:
  name: Panka

backend:
  baseUrl: https://genesis.panka.in
  listen: ':7007'

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

  cache:
    store: memory

integrations:
  gitlab:
    - host: git.panka.in
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://git.panka.in/api/v4
      baseUrl: https://git.panka.in

techdocs:
  builder: 'local' 
  runIn: 'docker'
  publisher:
    type: 'local' 


auth:
  environment: production
  providers:
    gitlab:
      production:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
        audience: https://git.panka.in

catalog:
  providers:
    gitlab:
      panka:
        host: git.panka.in
        branch: main
        projectPattern: '[\s\S]*'
        orgEnabled: true
        schedule: 
          frequency: { minutes: 30 }
          timeout: { minutes: 3 }
```
