### ISSUE TITLE
Nothing show up in the Gitlab Entity

### ISSUE THREAD

**Issue by Kaslie** [immobiliare/backstage-plugin-gitlab#15]
Hi, I am new to backstage, and trying to use this gitlab plugin. However, I encounter this issues. Please help. Thank you in advance.

Issues:
- Nothing show up in the Gitlab Entity
- No Gitlab GET Request from the log

Expected Result:
- Gitlab Entity Page show up as Intended with selected project-id defined in annotation

Config:
```
# app-config.yaml -> I supply those environment variables before run `yarn dev`
integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}

proxy:
  '/gitlabci':
    target: '${GITLAB_URL}/api/v4'
    allowedMethods: [ 'GET' ]
    headers:
      PRIVATE-TOKEN: '${GITLAB_TOKEN}'

# example/entities.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  annotations:
    gitlab.com/project-id: '39781451' 
spec:
  type: service
  owner: user:guest
  lifecycle: production

# packages/app/src/components/catalog/Gitlab.tsx
export const gitlabEntityPage = (
    <EntityLayout.Route if={isGitlabAvailable} path="/gitlab" title="Gitlab">
        <EntityGitlabContent />
    </EntityLayout.Route>
)

# packages/app/src/components/catalog/EntityPage.tsx
const serviceEntityPage = (
  <EntityLayout>
    ...
    {gitlabEntityPage}
  </EntityLayout>
);
```
No request to gitlab api After Visit the Entity, When I use `gitlab.com/project-slug` with wrong values, there are some GET Request log. I expected It works the same with correct values.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12933685/208296393-484d2461-e5fa-4488-b486-931fd683671f.png">

Empty Result on the page
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/12933685/208296415-b17e7d97-6a7f-4f31-8acb-92197caca317.png">

Thank you

**Comment by antoniomuso** [comment]
can you post the network errors in the browser? Have you allowed Gitlab in CORS ?

**Comment by Kaslie** [comment]
Nevermind, It works now without me doing anything, just left it for a day.

**Comment by Kaslie** [comment]
Thank you

**Comment by jsidney** [comment]
@antoniomuso  - i am having the same issue on my side. i am running the instance locally at the moment. I am able to import the entity (in this case a `Resource`) but I am not able to view anything in the cards. My network errors look like:
![image](https://user-images.githubusercontent.com/7551131/211777492-b236633b-749f-4eab-9bdf-ada33bce1848.png)

my service spec looks like this:
```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fargate-application
  description: Template for 3-tier serverless container application on AWS
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: 'synthesis2/fargate-application'
  links:
    - url: https://synthesis2.gitlab.io/fargate-application/
      title: 'Infracost Cost Breakdown'
      icon: dashboard
  tags:
    - terraform
    - hcl
    - aws
spec:
  type: service
  owner: group:synthesis-platform
  system: aws-app-templates
  lifecycle: production
```

**Comment by antoniomuso** [comment]
From what you have posted seems that your project slug needs to be corrected.

**Comment by jsidney** [comment]
> hi [jsidney](https://github.com/jsidney), from what you have posted seems that your project slug needs to be corrected. I suggest always using project-id.

thanks for the suggestion @antoniomuso . unfortunately it doesn't make a difference :(

**Comment by antoniomuso** [comment]
If you can, post Backstage logs and full networking browser logs. Have you configured the proxy?

**Comment by jsidney** [comment]
this is my proxy config:
```yaml
'/gitlabci':
    target: 'https://gitlab.com/api/v4'
    allowedMethods: ['GET']
    headers:
      PRIVATE_TOKEN: '${GITLAB_TOKEN}'
```
the backstage logs all look pretty much the same as this:
```
[1] 2023-01-11T11:05:40.619Z backstage info ::1 - - [11/Jan/2023:11:05:40 +0000] "GET /api/proxy/gitlabci/projects/40829771? HTTP/1.1" 404 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" type=incomingRequest
[1] 2023-01-11T11:05:41.449Z backstage info ::1 - - [11/Jan/2023:11:05:41 +0000] "GET /api/proxy/gitlabci/projects/40829771? HTTP/1.1" 404 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" type=incomingRequest
```
