### ISSUE TITLE
The gitlab plugin doesn't work with baseUrl

### ISSUE THREAD

**Issue by romph** [immobiliare/backstage-plugin-gitlab#275]
👋 I'm working on serving backstage behind a reverse proxy, everything seems ok despite this plugin.

Here are all the steps I did :

1. Installing backstage
2. Removing plugins (github action, techdoc)
3. Adding plugins (jenkins, sonarqube, gitlab, kafka)
4. Building as a container [multi-stage build](https://backstage.io/docs/deployment/docker#multi-stage-build) with NODE_TLS_REJECT_UNAUTHORIZED '0' as env (to avoid https issues)
5. Checking that everything is good without baseUrl - it's working
6. Adding baseUrl - not working

app-config.yaml
```
# FRONTEND_BASEURL=http://localhost:7007/instance/backstage
# BACKEND_BASEURL=http://localhost:7007/instance/backstage 
# GITLAB_HOST=my-custom-gitlab.com
# GITLAB_TOKEN=my-token
app:
  baseUrl: ${FRONTEND_BASEURL}
backend:
  baseUrl: ${BACKEND_BASEURL}
integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      baseUrl: https://${GITLAB_HOST}
      apiBaseUrl: https://${GITLAB_HOST}/api/v4
```
reverse-proxy.conf
```
<LocationMatch "^\/instance\/(?<backstage>[^\/]+)(\/?.*)">
    ProxyPass "http://$1:7007$2"
    ProxyPassReverse "http://$1:7007$2"
</LocationMatch>
# https://localhost/instance/backstage/catalog
# ProxyPass "http://backstage:7007/catalog"
# ProxyPassReverse "http://backstage:7007/catalog"
```
catalog-info.yaml
```
metadata:
  annotations:
    gitlab.com/project-id: '<gitlab-project-id>'
    gitlab.com/instance: '<my-custom-gitlab.com>'
```
**Troubleshooting** : it's as if the plugin doesn't directly request the gitlab api with the token

backstage.log
```
# The request goes well up to the backstage instance
GET /api/gitlab/<my-custom-gitlab.com>/projects/<gitlab-project-id>? HTTP/1.1\" 302
```
Inside backstage container
```
# docker exec -it backstage bash
curl http://localhost:7007/api/gitlab/<my-custom-gitlab.com>/projects/<gitlab-project-id>
# result
<html><body>You are being <a href="https://<my-custom-gitlab.com>/users/sign_in">redirected</a>.</body></html>
```
