### ISSUE TITLE
Error when using self hosted GitLab with subpath + GitLab filler processor

### ISSUE THREAD

**Issue by dfl-aeb** [immobiliare/backstage-plugin-gitlab#333]
I'm experiencing an issue because our self hosted gitlab instance runs under a subpath.
e.g. `git.company.com/gitlab` 

When trying to access `git.company.com/gitlab/genc/infrastructure/docker` the GitLab Filler Processor tries to call
`git.company.com/projects/gitlab/genc/infrastructure/docker` instead of `git.company.com/gitlab/projects/genc/infrastructure/docker`
--> 
`http://localhost:8080/api/gitlab/rest/git.company.com/projects/gitlab%2Fgenc%2Finfrastructure%2Fdocker`

Maybe related to: https://github.com/immobiliare/backstage-plugin-gitlab/issues/236

Everything else works fine, just the gitlab filler processor does not.

**Comment by antoniomuso** [comment]
Can you post your Backstage gitlab configurations?

**Comment by dfl-aeb** [comment]
```yaml
integrations:
  gitlab:
    - host: git.company.com
      apiBaseUrl: https://git.company.com/gitlab/api/v4
      baseUrl: https://git.company.com/gitlab
      token: ${GITLAB_TOKEN}
      
proxy:
  '/gitlabci':
    target: 'https://git.company.com/gitlab/api/v4'
    allowedMethods: ['GET', 'POST']
    headers:
      PRIVATE-TOKEN: '${GITLAB_TOKEN}'

gitlab: #for gitlab plugin: https://github.com/immobiliare/backstage-plugin-gitlab
  defaultCodeOwnersPath: .gitlab/CODEOWNERS

```
