### ISSUE TITLE
Getting error "wrong project_slug or project_id"

### ISSUE THREAD

**Issue by shirish539** [immobiliare/backstage-plugin-gitlab#715]
I have configured the GitLab plugin by following the doc https://github.com/immobiliare/backstage-plugin-gitlab. 

I have the private instance of Gitlab and the configuration is as below. 

**In app-config.yaml** 

```
integrations:
  gitlab:
    - host: 'myhost'
      token: 'XXXXXXXXXXXXXX'
      apiBaseUrl: 'https://my-domain/api/v4'
      allowedKinds: ['Component', 'Resource']

proxy:
    '/gitlab':
    target: https://my-domain
    headers:
      PRIVATE-TOKEN: 'XXXXXXXXXXXXXX'
    changeOrigin: true
    secure: true

```
**In Catalog-info.yaml I have :-** 

```
kind: Component
metadata:
  name: testApp
  tags:
    - lang:golang
  annotations:
    gitlab.com/project-id: '40520'  # Replace with your actual GitLab project ID
    #gitlab.com/project-slug: 'username/testapp' # group_name/project_name
```

I have verified that my project-id and Access token are correct. I am not able to understand what exactly I am doing wrong.
